FROM gradle:jdk21 as build

COPY --chown=gradle:gradle . /home/gradle/src

WORKDIR /home/gradle/src

RUN gradle build --no-daemon -x test

FROM eclipse-temurin:21-jre-jammy
EXPOSE 8080
RUN mkdir /app

COPY --from=build /home/gradle/src/build/libs/*.jar /app/spring-boot/application.jar
ENTRYPOINT [ "java", "-jar", "/app/spring-boot/application.jar" ]